MPESA_CONSUMER_KEY: 'dcyKHtJNWszUZPScSDqafRW8llXMRQGGGWzAtMqcOlR5ABco'
MPESA_CONSUMER_SECRET: 'TD9kermkwEiZjtdN49TeMtWAjAoRNsaTlxY5SWYifG1suSrMiZAv1rw1CaBA3nWY'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://2161-102-213-49-3.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"